name: SIGSEGV
description: Computer scientist (almost)

safe: true
lsi: false

url: 'https://piax93.github.io'
author: 'Matteo Piano'
email: 'piano.matteo@outlook.com'
linkedin: 'pianomatteo'
github: 'piax93'
twitter: 'piax93'
facebook: 'piax93'

background: '/resources/images/stockholm.png'
profile_avatar: '/resources/images/profile.png'

paginate: 5
paginate_path: '/page:num/'
markdown: kramdown

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

gems:
- jekyll-paginate
