name: 'SIGSEGV'
description: 'Computer scientist (almost)'

safe: true
lsi: false

url: 'https://piax93.github.io'
author: 'Matteo Piano'
linkedin: 'pianomatteo'
github: 'piax93'
twitter: 'piax93'
facebook: 'piax93'

excerpt_separator: '.'

background: '/resources/images/background.png'
profile_avatar: '/resources/images/profile.png'
favicon: '/resources/images/favicon.ico'

docs: '/resources/documents'
videos: '/resources/videos'
images: '/resources/images'

markdown: kramdown

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

nav:
  -
    name: 'DGI17 BLOG'
    href: '/dgi17'

