name: Matteo Piano
description: Computer scientist (almost).

safe: true
lsi: false

url: 'https://piax93.github.io'
author: 'Matteo Piano'
email: 'piano.matteo@outlook.com'
linkedin: 'pianomatteo'
githubnn: 'piax93'
twitter: 'piax93'
facebook: 'piax93'


background: 'http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg'

paginate: 5
paginate_path: '/page:num/'
markdown: kramdown

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

gems:
- jekyll-paginate
